# Generated by Django 3.1.3 on 2020-11-30 00:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('vendor', models.TextField()),
                ('url', models.URLField(max_length=100)),
                ('status', models.CharField(choices=[('LATEST', 'Latest'), ('UPDATE', 'Update'), ('CRITICAL', 'Critical'), ('UNKNOWN', 'Unknown'), ('ERROR', 'Error'), ('N/A', 'N/A')], default='N/A', max_length=20)),
                ('send_notification', models.BooleanField()),
                ('notified_at', models.DateTimeField()),
                ('acknowledged_at', models.DateTimeField()),
                ('acknowledged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='software_acknowledge_created', to=settings.AUTH_USER_MODEL)),
                ('maintainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='software_maintainer_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('status', models.CharField(choices=[('INVALID', 'Invalid'), ('VALID', 'Valid'), ('EXPIRED', 'Expired'), ('ERROR', 'Error'), ('N/A', 'N/A')], default='N/A', max_length=20)),
                ('send_notification', models.BooleanField()),
                ('notified_at', models.DateTimeField()),
                ('acknowledged_at', models.DateTimeField()),
                ('acknowledged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='certificate_acknowledge_created', to=settings.AUTH_USER_MODEL)),
                ('maintainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='certificate_maintainer_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
