# Generated by Django 3.1.3 on 2020-11-22 11:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('status', models.TextField(verbose_name=web.models.CertificateStatus)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('vendor', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CommonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_notification', models.BooleanField()),
                ('notified_at', models.DateTimeField()),
                ('acknowledged_at', models.DateTimeField()),
                ('acknowledged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='acknowledged', to=settings.AUTH_USER_MODEL)),
                ('maintainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='maintainer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
