# Generated by Django 3.1.3 on 2020-11-22 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='id',
        ),
        migrations.RemoveField(
            model_name='software',
            name='id',
        ),
        migrations.AddField(
            model_name='certificate',
            name='commoninfo_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.commoninfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software',
            name='commoninfo_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.commoninfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commoninfo',
            name='maintainer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='maintainer', to=settings.AUTH_USER_MODEL),
        ),
    ]
