# Generated by Django 2.1.15 on 2020-12-08 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20201130_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='domain',
            field=models.CharField(max_length=80, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
